# Generated by Django 6.0 on 2026-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('representative_name', models.CharField(max_length=200)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会社情報',
                'verbose_name_plural': '会社情報',
                'db_table': 'company_infos',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('published_on', models.DateField()),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会員規約',
                'verbose_name_plural': '会員規約',
                'db_table': 'terms_of_services',
                'ordering': ['-published_on', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='InforMation',
        ),
    ]
