# Generated by Django 6.0 on 2026-01-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_companyinfo_termsofservice_delete_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='companyinfo',
            table=None,
        ),
    ]
