# Generated by Django 6.0 on 2026-01-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_companyinfo_options_alter_companyinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': '会社情報', 'verbose_name_plural': '会社情報'},
        ),
        migrations.AlterModelTable(
            name='companyinfo',
            table='company_infos',
        ),
    ]
