# Generated by Django 6.0 on 2026-01-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_companyinfo_options_alter_companyinfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofservice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
