# Generated by Django 6.0 on 2026-01-05 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_store_reservation_review_storecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.store', verbose_name='店舗'),
        ),
    ]
