# Generated by Django 6.0 on 2026-01-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_memberprofile_occupation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': '会員', 'verbose_name_plural': '会員'},
        ),
    ]
